name: Check Critical Changes

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check_changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2  # Fetch enough history to find the base branch

    - name: Get base branch
      id: vars
      run: echo "BASE_BRANCH=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV

    - name: Run critical changes check
      run: |
        git fetch origin $BASE_BRANCH
        git diff origin/$BASE_BRANCH...HEAD > changes.diff
        critical_patterns=("iptables" "password" "ssh-key" "secret" "token")
        for pattern in "${critical_patterns[@]}"; do
          if grep -q -E "$pattern" changes.diff; then
            echo "Critical change detected: $pattern"
            exit 1
          fi
        done
        echo "No critical changes found."

    - name: Post comment if critical changes are detected
      if: failure()
      uses: actions/github-script@v3
      with:
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "🚨 Critical changes detected in this PR. Please review the changes carefully."
          })

